### PR TITLE
Validate signature on public/readonly instance (ref #29, #32)

### PR DESCRIPTION
**Pull request by leplatrem**
Ref #32 

Do not skip any collection if signer is not enabled and no info about signing resources can be obtained

### CODE REVIEW

**Comment by glasserc** [comment]
What? Do we know if the lambda runs against the public endpoint or the writer?

**Comment by leplatrem** [comment]
> What? Do we know if the lambda runs against the public endpoint or the writer?

It runs on the *reader* apparently:

https://github.com/mozilla-services/cloudops-deployment/blob/dc72e8241f5f721e49c054c8726a4fc4a7089b61/projects/kinto-lambda/ansible/playbooks/refresh_signature_lambda.yml#L15

https://github.com/mozilla-services/cloudops-deployment/blob/dc72e8241f5f721e49c054c8726a4fc4a7089b61/projects/kinto-lambda/ansible/playbooks/validate_signature_lambda.yml#L15

**Comment by glasserc** [comment]
Sorry, I got turned around and thought this was adding another reason why we would skip a collection, rather than removing one. Either way is fine. If you want to go with this solution, maybe add a note explicitly explaining the situation why we would validate signatures on even though kinto-signer capability isn't there (because it's a readonly clone I guess).

**Comment by leplatrem** [comment]
I think I prefer to remove this and go with something like a fix for #31

**Pull request merged**
